// Generated by scripts/generate-db-types.mjs. Do not edit by hand.
//
// Regenerate after every migration:
//   npm run db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      assignments: {
        Row: {
          id: string;
          instructor_id: string | null;
          student_id: string | null;
          lesson_id: string | null;
          practice_set_id: string | null;
          due_at: string | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          instructor_id?: string | null;
          student_id?: string | null;
          lesson_id?: string | null;
          practice_set_id?: string | null;
          due_at?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          instructor_id?: string | null;
          student_id?: string | null;
          lesson_id?: string | null;
          practice_set_id?: string | null;
          due_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      attempt_responses: {
        Row: {
          id: string;
          attempt_id: string | null;
          question_version_id: string | null;
          answer: Json;
          score: number | null;
          time_seconds: number | null;
          feedback: Json | null;
        };
        Insert: {
          id?: string;
          attempt_id?: string | null;
          question_version_id?: string | null;
          answer: Json;
          score?: number | null;
          time_seconds?: number | null;
          feedback?: Json | null;
        };
        Update: {
          id?: string;
          attempt_id?: string | null;
          question_version_id?: string | null;
          answer?: Json;
          score?: number | null;
          time_seconds?: number | null;
          feedback?: Json | null;
        };
        Relationships: [];
      };
      attempts: {
        Row: {
          id: string;
          user_id: string;
          practice_set_id: string | null;
          mock_exam_id: string | null;
          exam_version_id: string | null;
          started_at: string | null;
          submitted_at: string | null;
          score: number | null;
          estimate: Json | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          practice_set_id?: string | null;
          mock_exam_id?: string | null;
          exam_version_id?: string | null;
          started_at?: string | null;
          submitted_at?: string | null;
          score?: number | null;
          estimate?: Json | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          practice_set_id?: string | null;
          mock_exam_id?: string | null;
          exam_version_id?: string | null;
          started_at?: string | null;
          submitted_at?: string | null;
          score?: number | null;
          estimate?: Json | null;
        };
        Relationships: [];
      };
      audio_assets: {
        Row: {
          id: string;
          title: string;
          storage_path: string | null;
          generated: boolean | null;
          speaker_info: Json | null;
          accent_region: string | null;
          cefr_level: string | null;
          duration_seconds: number | null;
          source_id: string | null;
          copyright_status: string | null;
          skills: Database["public"]["Enums"]["skill_code"][] | null;
          exam_tags: Database["public"]["Enums"]["exam_code"][] | null;
          status: Database["public"]["Enums"]["content_status"] | null;
        };
        Insert: {
          id?: string;
          title: string;
          storage_path?: string | null;
          generated?: boolean | null;
          speaker_info?: Json | null;
          accent_region?: string | null;
          cefr_level?: string | null;
          duration_seconds?: number | null;
          source_id?: string | null;
          copyright_status?: string | null;
          skills?: Database["public"]["Enums"]["skill_code"][] | null;
          exam_tags?: Database["public"]["Enums"]["exam_code"][] | null;
          status?: Database["public"]["Enums"]["content_status"] | null;
        };
        Update: {
          id?: string;
          title?: string;
          storage_path?: string | null;
          generated?: boolean | null;
          speaker_info?: Json | null;
          accent_region?: string | null;
          cefr_level?: string | null;
          duration_seconds?: number | null;
          source_id?: string | null;
          copyright_status?: string | null;
          skills?: Database["public"]["Enums"]["skill_code"][] | null;
          exam_tags?: Database["public"]["Enums"]["exam_code"][] | null;
          status?: Database["public"]["Enums"]["content_status"] | null;
        };
        Relationships: [];
      };
      audio_transcripts: {
        Row: {
          id: string;
          audio_id: string;
          version: number;
          segments: Json;
          language: string | null;
        };
        Insert: {
          id?: string;
          audio_id: string;
          version: number;
          segments: Json;
          language?: string | null;
        };
        Update: {
          id?: string;
          audio_id?: string;
          version?: number;
          segments?: Json;
          language?: string | null;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: number;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          changes: Json;
          created_at: string | null;
        };
        Insert: {
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          changes?: Json;
          created_at?: string | null;
        };
        Update: {
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          changes?: Json;
          created_at?: string | null;
        };
        Relationships: [];
      };
      chunk_embeddings: {
        Row: {
          id: string;
          chunk_id: string;
          provider: string;
          model: string;
          dimensions: number;
          embedding: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          chunk_id: string;
          provider: string;
          model: string;
          dimensions: number;
          embedding: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          chunk_id?: string;
          provider?: string;
          model?: string;
          dimensions?: number;
          embedding?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      collocations: {
        Row: {
          id: string;
          left_term: string;
          right_term: string;
          meaning: Json;
          cefr_level: string | null;
        };
        Insert: {
          id?: string;
          left_term: string;
          right_term: string;
          meaning: Json;
          cefr_level?: string | null;
        };
        Update: {
          id?: string;
          left_term?: string;
          right_term?: string;
          meaning?: Json;
          cefr_level?: string | null;
        };
        Relationships: [];
      };
      concept_exam_tasks: {
        Row: {
          concept_id: string;
          exam_task_id: string;
          application_notes: string | null;
        };
        Insert: {
          concept_id: string;
          exam_task_id: string;
          application_notes?: string | null;
        };
        Update: {
          concept_id?: string;
          exam_task_id?: string;
          application_notes?: string | null;
        };
        Relationships: [];
      };
      concepts: {
        Row: {
          id: string;
          stable_key: string;
          kind: string;
          title: string;
          cefr_level: string;
          status: Database["public"]["Enums"]["content_status"];
          current_version: number;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          stable_key: string;
          kind: string;
          title: string;
          cefr_level: string;
          status?: Database["public"]["Enums"]["content_status"];
          current_version?: number;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          stable_key?: string;
          kind?: string;
          title?: string;
          cefr_level?: string;
          status?: Database["public"]["Enums"]["content_status"];
          current_version?: number;
          created_by?: string | null;
        };
        Relationships: [];
      };
      content_versions: {
        Row: {
          id: string;
          concept_id: string;
          version: number;
          content: Json;
          prompt_version: string | null;
          model_metadata: Json | null;
          created_by: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          concept_id: string;
          version: number;
          content: Json;
          prompt_version?: string | null;
          model_metadata?: Json | null;
          created_by?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          concept_id?: string;
          version?: number;
          content?: Json;
          prompt_version?: string | null;
          model_metadata?: Json | null;
          created_by?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      document_chunks: {
        Row: {
          id: string;
          source_file_id: string;
          chunk_index: number;
          page_from: number;
          page_to: number;
          heading: string | null;
          text: string;
          token_count: number | null;
          created_at: string;
          search_vector: string | null;
        };
        Insert: {
          id?: string;
          source_file_id: string;
          chunk_index: number;
          page_from: number;
          page_to: number;
          heading?: string | null;
          text: string;
          token_count?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_file_id?: string;
          chunk_index?: number;
          page_from?: number;
          page_to?: number;
          heading?: string | null;
          text?: string;
          token_count?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      document_pages: {
        Row: {
          id: string;
          source_file_id: string;
          page_number: number;
          text: string;
          char_count: number;
          extraction_method: Database["public"]["Enums"]["extraction_method"];
          confidence: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_file_id: string;
          page_number: number;
          text: string;
          char_count?: number;
          extraction_method: Database["public"]["Enums"]["extraction_method"];
          confidence?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_file_id?: string;
          page_number?: number;
          text?: string;
          char_count?: number;
          extraction_method?: Database["public"]["Enums"]["extraction_method"];
          confidence?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      exam_sections: {
        Row: {
          id: string;
          exam_version_id: string;
          skill: Database["public"]["Enums"]["skill_code"];
          title: string;
          position: number;
          question_count: number | null;
          duration_seconds: number;
          navigation_rules: Json;
          audio_replay_limit: number | null;
          scoring_scale: Json;
        };
        Insert: {
          id?: string;
          exam_version_id: string;
          skill: Database["public"]["Enums"]["skill_code"];
          title: string;
          position: number;
          question_count?: number | null;
          duration_seconds: number;
          navigation_rules?: Json;
          audio_replay_limit?: number | null;
          scoring_scale?: Json;
        };
        Update: {
          id?: string;
          exam_version_id?: string;
          skill?: Database["public"]["Enums"]["skill_code"];
          title?: string;
          position?: number;
          question_count?: number | null;
          duration_seconds?: number;
          navigation_rules?: Json;
          audio_replay_limit?: number | null;
          scoring_scale?: Json;
        };
        Relationships: [];
      };
      exam_tasks: {
        Row: {
          id: string;
          section_id: string;
          code: string;
          title: string;
          position: number;
          preparation_seconds: number | null;
          word_min: number | null;
          word_max: number | null;
          instructions: string;
          settings: Json;
        };
        Insert: {
          id?: string;
          section_id: string;
          code: string;
          title: string;
          position: number;
          preparation_seconds?: number | null;
          word_min?: number | null;
          word_max?: number | null;
          instructions: string;
          settings?: Json;
        };
        Update: {
          id?: string;
          section_id?: string;
          code?: string;
          title?: string;
          position?: number;
          preparation_seconds?: number | null;
          word_min?: number | null;
          word_max?: number | null;
          instructions?: string;
          settings?: Json;
        };
        Relationships: [];
      };
      exam_versions: {
        Row: {
          id: string;
          exam_id: string;
          version: string;
          valid_from: string;
          source_url: string | null;
          administrative_notes: string | null;
          is_active: boolean;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          exam_id: string;
          version: string;
          valid_from: string;
          source_url?: string | null;
          administrative_notes?: string | null;
          is_active?: boolean;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          exam_id?: string;
          version?: string;
          valid_from?: string;
          source_url?: string | null;
          administrative_notes?: string | null;
          is_active?: boolean;
          created_at?: string | null;
        };
        Relationships: [];
      };
      exams: {
        Row: {
          id: string;
          code: Database["public"]["Enums"]["exam_code"];
          name: string;
        };
        Insert: {
          id?: string;
          code: Database["public"]["Enums"]["exam_code"];
          name: string;
        };
        Update: {
          id?: string;
          code?: Database["public"]["Enums"]["exam_code"];
          name?: string;
        };
        Relationships: [];
      };
      feedback_records: {
        Row: {
          id: string;
          writing_id: string | null;
          speaking_id: string | null;
          reviewer_id: string | null;
          rubric: Json;
          annotations: Json | null;
          corrected_version: string | null;
          model_version: string | null;
          prompt_version: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          writing_id?: string | null;
          speaking_id?: string | null;
          reviewer_id?: string | null;
          rubric: Json;
          annotations?: Json | null;
          corrected_version?: string | null;
          model_version?: string | null;
          prompt_version?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          writing_id?: string | null;
          speaking_id?: string | null;
          reviewer_id?: string | null;
          rubric?: Json;
          annotations?: Json | null;
          corrected_version?: string | null;
          model_version?: string | null;
          prompt_version?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      ingestion_events: {
        Row: {
          id: number;
          job_id: string;
          stage: string;
          status: Database["public"]["Enums"]["processing_status"];
          message: string | null;
          details: Json;
          created_at: string;
        };
        Insert: {
          job_id: string;
          stage: string;
          status: Database["public"]["Enums"]["processing_status"];
          message?: string | null;
          details?: Json;
          created_at?: string;
        };
        Update: {
          job_id?: string;
          stage?: string;
          status?: Database["public"]["Enums"]["processing_status"];
          message?: string | null;
          details?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      ingestion_jobs: {
        Row: {
          id: string;
          source_file_id: string;
          status: Database["public"]["Enums"]["processing_status"];
          stage: string | null;
          error_code: string | null;
          metadata: Json | null;
          started_at: string | null;
          finished_at: string | null;
          attempts: number;
          next_retry_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_file_id: string;
          status?: Database["public"]["Enums"]["processing_status"];
          stage?: string | null;
          error_code?: string | null;
          metadata?: Json | null;
          started_at?: string | null;
          finished_at?: string | null;
          attempts?: number;
          next_retry_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_file_id?: string;
          status?: Database["public"]["Enums"]["processing_status"];
          stage?: string | null;
          error_code?: string | null;
          metadata?: Json | null;
          started_at?: string | null;
          finished_at?: string | null;
          attempts?: number;
          next_retry_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      lesson_concepts: {
        Row: {
          lesson_id: string;
          concept_id: string;
          position: number;
          exam_label: string;
        };
        Insert: {
          lesson_id: string;
          concept_id: string;
          position: number;
          exam_label: string;
        };
        Update: {
          lesson_id?: string;
          concept_id?: string;
          position?: number;
          exam_label?: string;
        };
        Relationships: [];
      };
      lesson_versions: {
        Row: {
          id: string;
          lesson_id: string;
          version: number;
          blocks: Json;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          version: number;
          blocks: Json;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          version?: number;
          blocks?: Json;
          created_at?: string | null;
        };
        Relationships: [];
      };
      lessons: {
        Row: {
          id: string;
          slug: string;
          title: string;
          cefr_level: string;
          primary_skill: Database["public"]["Enums"]["skill_code"];
          duration_minutes: number;
          status: Database["public"]["Enums"]["content_status"];
          current_version: number;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          cefr_level: string;
          primary_skill: Database["public"]["Enums"]["skill_code"];
          duration_minutes: number;
          status?: Database["public"]["Enums"]["content_status"];
          current_version?: number;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          cefr_level?: string;
          primary_skill?: Database["public"]["Enums"]["skill_code"];
          duration_minutes?: number;
          status?: Database["public"]["Enums"]["content_status"];
          current_version?: number;
          created_by?: string | null;
        };
        Relationships: [];
      };
      mistake_records: {
        Row: {
          id: string;
          user_id: string | null;
          response_id: string | null;
          category: string;
          original_answer: Json | null;
          correct_answer: Json | null;
          explanation: string | null;
          skill: Database["public"]["Enums"]["skill_code"] | null;
          exam: Database["public"]["Enums"]["exam_code"] | null;
          repetitions: number | null;
          mastery: number | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          response_id?: string | null;
          category: string;
          original_answer?: Json | null;
          correct_answer?: Json | null;
          explanation?: string | null;
          skill?: Database["public"]["Enums"]["skill_code"] | null;
          exam?: Database["public"]["Enums"]["exam_code"] | null;
          repetitions?: number | null;
          mastery?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          response_id?: string | null;
          category?: string;
          original_answer?: Json | null;
          correct_answer?: Json | null;
          explanation?: string | null;
          skill?: Database["public"]["Enums"]["skill_code"] | null;
          exam?: Database["public"]["Enums"]["exam_code"] | null;
          repetitions?: number | null;
          mastery?: number | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      mock_exam_sections: {
        Row: {
          mock_exam_id: string;
          exam_section_id: string | null;
          practice_set_id: string | null;
          position: number;
        };
        Insert: {
          mock_exam_id: string;
          exam_section_id?: string | null;
          practice_set_id?: string | null;
          position: number;
        };
        Update: {
          mock_exam_id?: string;
          exam_section_id?: string | null;
          practice_set_id?: string | null;
          position?: number;
        };
        Relationships: [];
      };
      mock_exams: {
        Row: {
          id: string;
          title: string;
          exam_version_id: string;
          status: Database["public"]["Enums"]["content_status"] | null;
          settings: Json | null;
        };
        Insert: {
          id?: string;
          title: string;
          exam_version_id: string;
          status?: Database["public"]["Enums"]["content_status"] | null;
          settings?: Json | null;
        };
        Update: {
          id?: string;
          title?: string;
          exam_version_id?: string;
          status?: Database["public"]["Enums"]["content_status"] | null;
          settings?: Json | null;
        };
        Relationships: [];
      };
      phrases: {
        Row: {
          id: string;
          text: string;
          meaning: Json;
          cefr_level: string | null;
        };
        Insert: {
          id?: string;
          text: string;
          meaning: Json;
          cefr_level?: string | null;
        };
        Update: {
          id?: string;
          text?: string;
          meaning?: Json;
          cefr_level?: string | null;
        };
        Relationships: [];
      };
      practice_set_questions: {
        Row: {
          practice_set_id: string;
          question_version_id: string | null;
          position: number;
        };
        Insert: {
          practice_set_id: string;
          question_version_id?: string | null;
          position: number;
        };
        Update: {
          practice_set_id?: string;
          question_version_id?: string | null;
          position?: number;
        };
        Relationships: [];
      };
      practice_sets: {
        Row: {
          id: string;
          title: string;
          exam_version_id: string | null;
          mode: string;
          status: Database["public"]["Enums"]["content_status"] | null;
          settings: Json | null;
        };
        Insert: {
          id?: string;
          title: string;
          exam_version_id?: string | null;
          mode: string;
          status?: Database["public"]["Enums"]["content_status"] | null;
          settings?: Json | null;
        };
        Update: {
          id?: string;
          title?: string;
          exam_version_id?: string | null;
          mode?: string;
          status?: Database["public"]["Enums"]["content_status"] | null;
          settings?: Json | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          locale: string;
          timezone: string;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          locale?: string;
          timezone?: string;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          locale?: string;
          timezone?: string;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      question_choices: {
        Row: {
          id: string;
          question_version_id: string | null;
          stable_key: string;
          label: string;
          position: number;
          is_correct: boolean;
          explanation: string | null;
        };
        Insert: {
          id?: string;
          question_version_id?: string | null;
          stable_key: string;
          label: string;
          position: number;
          is_correct?: boolean;
          explanation?: string | null;
        };
        Update: {
          id?: string;
          question_version_id?: string | null;
          stable_key?: string;
          label?: string;
          position?: number;
          is_correct?: boolean;
          explanation?: string | null;
        };
        Relationships: [];
      };
      question_evidence: {
        Row: {
          id: string;
          question_version_id: string | null;
          source_file_id: string | null;
          page_number: number | null;
          evidence_text: string;
          locator: Json | null;
        };
        Insert: {
          id?: string;
          question_version_id?: string | null;
          source_file_id?: string | null;
          page_number?: number | null;
          evidence_text: string;
          locator?: Json | null;
        };
        Update: {
          id?: string;
          question_version_id?: string | null;
          source_file_id?: string | null;
          page_number?: number | null;
          evidence_text?: string;
          locator?: Json | null;
        };
        Relationships: [];
      };
      question_versions: {
        Row: {
          id: string;
          question_id: string | null;
          version: number;
          kind: string;
          prompt: string;
          difficulty: number | null;
          content: Json;
          correct_answer: Json | null;
          explanation: string | null;
          distractor_explanations: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          question_id?: string | null;
          version: number;
          kind: string;
          prompt: string;
          difficulty?: number | null;
          content?: Json;
          correct_answer?: Json | null;
          explanation?: string | null;
          distractor_explanations?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          question_id?: string | null;
          version?: number;
          kind?: string;
          prompt?: string;
          difficulty?: number | null;
          content?: Json;
          correct_answer?: Json | null;
          explanation?: string | null;
          distractor_explanations?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      questions: {
        Row: {
          id: string;
          stable_key: string;
          skill: Database["public"]["Enums"]["skill_code"];
          status: Database["public"]["Enums"]["content_status"] | null;
          current_version: number | null;
          usage_count: number | null;
        };
        Insert: {
          id?: string;
          stable_key: string;
          skill: Database["public"]["Enums"]["skill_code"];
          status?: Database["public"]["Enums"]["content_status"] | null;
          current_version?: number | null;
          usage_count?: number | null;
        };
        Update: {
          id?: string;
          stable_key?: string;
          skill?: Database["public"]["Enums"]["skill_code"];
          status?: Database["public"]["Enums"]["content_status"] | null;
          current_version?: number | null;
          usage_count?: number | null;
        };
        Relationships: [];
      };
      reading_passage_versions: {
        Row: {
          id: string;
          passage_id: string | null;
          version: number;
          body: string;
          word_count: number;
        };
        Insert: {
          id?: string;
          passage_id?: string | null;
          version: number;
          body: string;
          word_count: number;
        };
        Update: {
          id?: string;
          passage_id?: string | null;
          version?: number;
          body?: string;
          word_count?: number;
        };
        Relationships: [];
      };
      reading_passages: {
        Row: {
          id: string;
          title: string;
          passage_type: string;
          cefr_level: string;
          status: Database["public"]["Enums"]["content_status"] | null;
          current_version: number | null;
          source_id: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          passage_type: string;
          cefr_level: string;
          status?: Database["public"]["Enums"]["content_status"] | null;
          current_version?: number | null;
          source_id?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          passage_type?: string;
          cefr_level?: string;
          status?: Database["public"]["Enums"]["content_status"] | null;
          current_version?: number | null;
          source_id?: string | null;
        };
        Relationships: [];
      };
      retrieval_queries: {
        Row: {
          id: string;
          actor_id: string | null;
          query_text: string;
          strategy: string;
          chunk_ids: string[];
          result_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          query_text: string;
          strategy: string;
          chunk_ids?: string[];
          result_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          query_text?: string;
          strategy?: string;
          chunk_ids?: string[];
          result_count?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      review_cards: {
        Row: {
          id: string;
          user_id: string | null;
          kind: string;
          front: Json;
          back: Json;
          due_at: string | null;
          interval_days: number | null;
          ease: number | null;
          source_mistake_id: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          kind: string;
          front: Json;
          back: Json;
          due_at?: string | null;
          interval_days?: number | null;
          ease?: number | null;
          source_mistake_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          kind?: string;
          front?: Json;
          back?: Json;
          due_at?: string | null;
          interval_days?: number | null;
          ease?: number | null;
          source_mistake_id?: string | null;
        };
        Relationships: [];
      };
      review_events: {
        Row: {
          id: number;
          card_id: string | null;
          rating: number | null;
          reviewed_at: string | null;
        };
        Insert: {
          card_id?: string | null;
          rating?: number | null;
          reviewed_at?: string | null;
        };
        Update: {
          card_id?: string | null;
          rating?: number | null;
          reviewed_at?: string | null;
        };
        Relationships: [];
      };
      source_files: {
        Row: {
          id: string;
          source_id: string;
          version: number;
          original_filename: string;
          storage_path: string;
          mime_type: string;
          byte_size: number;
          page_count: number | null;
          sha256: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          source_id: string;
          version: number;
          original_filename: string;
          storage_path: string;
          mime_type: string;
          byte_size: number;
          page_count?: number | null;
          sha256: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          source_id?: string;
          version?: number;
          original_filename?: string;
          storage_path?: string;
          mime_type?: string;
          byte_size?: number;
          page_count?: number | null;
          sha256?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      source_materials: {
        Row: {
          id: string;
          title: string;
          author: string | null;
          publisher: string | null;
          publication_year: number | null;
          copyright_status: string;
          license_notes: string | null;
          language: string | null;
          cefr_level: string | null;
          skills: Database["public"]["Enums"]["skill_code"][] | null;
          topics: string[] | null;
          exam_relevance: Database["public"]["Enums"]["exam_code"][] | null;
          student_file_access: boolean;
          status: Database["public"]["Enums"]["content_status"];
          created_by: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          author?: string | null;
          publisher?: string | null;
          publication_year?: number | null;
          copyright_status: string;
          license_notes?: string | null;
          language?: string | null;
          cefr_level?: string | null;
          skills?: Database["public"]["Enums"]["skill_code"][] | null;
          topics?: string[] | null;
          exam_relevance?: Database["public"]["Enums"]["exam_code"][] | null;
          student_file_access?: boolean;
          status?: Database["public"]["Enums"]["content_status"];
          created_by?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          author?: string | null;
          publisher?: string | null;
          publication_year?: number | null;
          copyright_status?: string;
          license_notes?: string | null;
          language?: string | null;
          cefr_level?: string | null;
          skills?: Database["public"]["Enums"]["skill_code"][] | null;
          topics?: string[] | null;
          exam_relevance?: Database["public"]["Enums"]["exam_code"][] | null;
          student_file_access?: boolean;
          status?: Database["public"]["Enums"]["content_status"];
          created_by?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      speaking_submissions: {
        Row: {
          id: string;
          user_id: string | null;
          exam_task_id: string | null;
          storage_path: string;
          duration_seconds: number | null;
          transcript: string | null;
          submitted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          exam_task_id?: string | null;
          storage_path: string;
          duration_seconds?: number | null;
          transcript?: string | null;
          submitted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          exam_task_id?: string | null;
          storage_path?: string;
          duration_seconds?: number | null;
          transcript?: string | null;
          submitted_at?: string | null;
        };
        Relationships: [];
      };
      student_goals: {
        Row: {
          user_id: string;
          exam_goal: string;
          current_cefr: string;
          target_cefr: string;
          target_nclc: number | null;
          exam_date: string | null;
          study_days: string[];
          minutes_per_day: number;
          strongest_skill: Database["public"]["Enums"]["skill_code"] | null;
          weakest_skill: Database["public"]["Enums"]["skill_code"] | null;
          explanation_language: string;
          updated_at: string | null;
        };
        Insert: {
          user_id: string;
          exam_goal: string;
          current_cefr: string;
          target_cefr: string;
          target_nclc?: number | null;
          exam_date?: string | null;
          study_days?: string[];
          minutes_per_day: number;
          strongest_skill?: Database["public"]["Enums"]["skill_code"] | null;
          weakest_skill?: Database["public"]["Enums"]["skill_code"] | null;
          explanation_language: string;
          updated_at?: string | null;
        };
        Update: {
          user_id?: string;
          exam_goal?: string;
          current_cefr?: string;
          target_cefr?: string;
          target_nclc?: number | null;
          exam_date?: string | null;
          study_days?: string[];
          minutes_per_day?: number;
          strongest_skill?: Database["public"]["Enums"]["skill_code"] | null;
          weakest_skill?: Database["public"]["Enums"]["skill_code"] | null;
          explanation_language?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      study_plans: {
        Row: {
          id: string;
          user_id: string | null;
          start_date: string;
          end_date: string;
          plan: Json;
          status: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          start_date: string;
          end_date: string;
          plan: Json;
          status?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          start_date?: string;
          end_date?: string;
          plan?: Json;
          status?: string | null;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
        };
        Insert: {
          user_id: string;
          role?: Database["public"]["Enums"]["app_role"];
        };
        Update: {
          user_id?: string;
          role?: Database["public"]["Enums"]["app_role"];
        };
        Relationships: [];
      };
      vocabulary_entries: {
        Row: {
          id: string;
          lemma: string;
          language: string;
          cefr_level: string | null;
          definition: Json;
          pronunciation: Json | null;
        };
        Insert: {
          id?: string;
          lemma: string;
          language?: string;
          cefr_level?: string | null;
          definition: Json;
          pronunciation?: Json | null;
        };
        Update: {
          id?: string;
          lemma?: string;
          language?: string;
          cefr_level?: string | null;
          definition?: Json;
          pronunciation?: Json | null;
        };
        Relationships: [];
      };
      writing_submissions: {
        Row: {
          id: string;
          user_id: string | null;
          exam_task_id: string | null;
          original_text: string;
          word_count: number;
          submitted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          exam_task_id?: string | null;
          original_text: string;
          word_count: number;
          submitted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          exam_task_id?: string | null;
          original_text?: string;
          word_count?: number;
          submitted_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      attempt_review: {
        /** target_attempt_id uuid */
        Args: Record<string, unknown>;
        /** returns jsonb */
        Returns: unknown;
      };
      create_profile: {
        /** no arguments */
        Args: Record<string, unknown>;
        /** returns trigger */
        Returns: unknown;
      };
      has_role: {
        /** required_role app_role */
        Args: Record<string, unknown>;
        /** returns boolean */
        Returns: unknown;
      };
      is_instructor: {
        /** no arguments */
        Args: Record<string, unknown>;
        /** returns boolean */
        Returns: unknown;
      };
      is_staff: {
        /** no arguments */
        Args: Record<string, unknown>;
        /** returns boolean */
        Returns: unknown;
      };
      record_audit_event: {
        /** no arguments */
        Args: Record<string, unknown>;
        /** returns trigger */
        Returns: unknown;
      };
      search_source_chunks: {
        /** query_embedding vector, match_limit integer DEFAULT 8, min_similarity numeric DEFAULT 0.25 */
        Args: Record<string, unknown>;
        /** returns TABLE(chunk_id uuid, source_id uuid, source_title text, source_file_id uuid, source_version integer, page_from integer, page_to integer, heading text, text text, similarity numeric) */
        Returns: unknown;
      };
      staff_question_full: {
        /** target_version_id uuid */
        Args: Record<string, unknown>;
        /** returns jsonb */
        Returns: unknown;
      };
      submit_attempt_response: {
        /** target_attempt_id uuid, target_version_id uuid, learner_answer jsonb, seconds_spent integer DEFAULT NULL::integer */
        Args: Record<string, unknown>;
        /** returns jsonb */
        Returns: unknown;
      };
      touch_updated_at: {
        /** no arguments */
        Args: Record<string, unknown>;
        /** returns trigger */
        Returns: unknown;
      };
    };
    Enums: {
      app_role: "student" | "instructor" | "editor" | "admin";
      content_status: "draft" | "in_review" | "published" | "archived";
      exam_code: "TEF_CANADA" | "TCF_CANADA";
      extraction_method: "native" | "ocr" | "manual";
      processing_status: "pending" | "processing" | "needs_review" | "complete" | "failed";
      skill_code: "LISTENING" | "READING" | "WRITING" | "SPEAKING" | "GRAMMAR" | "VOCABULARY";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
