"use client";
import { useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Check, ChevronLeft, ChevronRight } from "lucide-react";
import { onboardingSchema, type OnboardingInput } from "@/lib/validation/onboarding";
import { createClient } from "@/lib/supabase/client";

const days=["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"];
const skills=[{v:"LISTENING",l:"Compréhension orale"},{v:"READING",l:"Compréhension écrite"},{v:"WRITING",l:"Expression écrite"},{v:"SPEAKING",l:"Expression orale"}] as const;

export function OnboardingForm({ configured }: { configured: boolean }) {
  const [step,setStep]=useState(1); const [message,setMessage]=useState("");
  const {register,handleSubmit,control,formState:{errors,isSubmitting}}=useForm<OnboardingInput>({resolver:zodResolver(onboardingSchema),defaultValues:{examGoal:"BOTH",currentLevel:"B1",targetLevel:"B2",targetNclc:7,studyDays:["Lun","Mar","Jeu","Sam"],minutesPerDay:30,strongestSkill:"READING",weakestSkill:"SPEAKING",explanationLanguage:"fr"}});
  const examGoal=useWatch({control,name:"examGoal"}); const studyDays=useWatch({control,name:"studyDays"}); const minutes=useWatch({control,name:"minutesPerDay"});
  const onSubmit=async(values:OnboardingInput)=>{if(!configured){localStorage.setItem("parcours-onboarding-demo",JSON.stringify(values));setMessage("Préférences enregistrées sur cet appareil en mode démonstration.");return} const client=createClient(); const {data:{user}}=await client.auth.getUser(); if(!user){setMessage("Votre session a expiré. Reconnectez-vous.");return} const {error}=await client.from("student_goals").upsert({user_id:user.id,...{exam_goal:values.examGoal,current_cefr:values.currentLevel,target_cefr:values.targetLevel,target_nclc:values.targetNclc,exam_date:values.examDate||null,study_days:values.studyDays,minutes_per_day:values.minutesPerDay,strongest_skill:values.strongestSkill,weakest_skill:values.weakestSkill,explanation_language:values.explanationLanguage}});setMessage(error?"Impossible d’enregistrer vos préférences.":"Votre parcours personnalisé est prêt.")};
  return <form className="onboarding-card" onSubmit={handleSubmit(onSubmit)}><div className="stepper">{[1,2,3].map(i=><span key={i} className={i<=step?"active":""}>{i<step?<Check/>:i}</span>)}</div>
    {step===1&&<fieldset><legend>Quel examen préparez-vous&nbsp;?</legend><p>Vous pourrez modifier ce choix à tout moment.</p><div className="choice-grid">{[["TEF_CANADA","TEF Canada"],["TCF_CANADA","TCF Canada"],["BOTH","Les deux examens"]].map(([v,l])=><label key={v} className={examGoal===v?"chosen":""}><input type="radio" value={v} {...register("examGoal")}/><strong>{l}</strong></label>)}</div><div className="form-grid"><label>Niveau actuel<select {...register("currentLevel")}>{["A1","A2","B1","B2","C1","C2"].map(x=><option key={x}>{x}</option>)}</select></label><label>Niveau cible<select {...register("targetLevel")}>{["A1","A2","B1","B2","C1","C2"].map(x=><option key={x}>{x}</option>)}</select></label><label>NCLC cible<input type="number" min="1" max="12" {...register("targetNclc",{valueAsNumber:true})}/></label><label>Date d’examen (facultative)<input type="date" {...register("examDate")}/></label></div></fieldset>}
    {step===2&&<fieldset><legend>Construisons votre rythme</legend><p>Un programme réaliste favorise la régularité sans pénalité.</p><div className="day-picker">{days.map(d=><label key={d} className={studyDays?.includes(d)?"chosen":""}><input type="checkbox" value={d} {...register("studyDays")}/>{d}</label>)}</div>{errors.studyDays&&<small className="form-error">{errors.studyDays.message}</small>}<label>Minutes disponibles par jour<input type="range" min="10" max="120" step="5" {...register("minutesPerDay",{valueAsNumber:true})}/><strong>{minutes} minutes</strong></label></fieldset>}
    {step===3&&<fieldset><legend>Adaptons les explications</legend><div className="form-grid"><label>Votre point fort<select {...register("strongestSkill")}>{skills.map(s=><option value={s.v} key={s.v}>{s.l}</option>)}</select></label><label>Votre priorité<select {...register("weakestSkill")}>{skills.map(s=><option value={s.v} key={s.v}>{s.l}</option>)}</select></label><label>Langue des explications<select {...register("explanationLanguage")}><option value="fr">Français</option><option value="en">English</option><option value="fa">فارسی</option></select></label></div>{errors.weakestSkill&&<small className="form-error">{errors.weakestSkill.message}</small>}</fieldset>}
    {message&&<div role="status" className="form-success">{message}</div>}<div className="form-actions">{step>1&&<button type="button" className="outline" onClick={()=>setStep(step-1)}><ChevronLeft/>Retour</button>} {step<3?<button type="button" className="primary" onClick={()=>setStep(step+1)}>Continuer<ChevronRight/></button>:<button className="primary" disabled={isSubmitting}>{isSubmitting?"Enregistrement…":"Créer mon programme"}</button>}</div></form>
}
